---
- name: Send successful deployment notification to Slack
  slack:
    token: "{{ slack_webhook_token }}"
    channel: slack_webhook_channel
    attachments:
      - text: "*{{ lookup('pipe', 'git config user.name') }}* successfully deployed {{ site }} to *<https://{{ project.site_hosts | map(attribute='canonical') | first }}|{{ env }}>* [<{{ slack_git_repo_url }}/commit/{{ git_clone.after }}|deployed commit>]"
        color: good
  when: slack_webhook_token is defined and slack_webhook_token != ""
  delegate_to: localhost
