---
- name: Send initial deployment notification to Slack
  slack:
    token: "{{ slack_deploy_token }}"
    attachments:
      - text: "*{{ lookup('pipe', 'git config user.name') }}* has started deploying {{ site }} to *<https://{{ project.site_hosts | map(attribute='canonical') | first }}|{{ env }}>*"
        color: warning
  with_items: "{{ vault_wordpress_sites[site].slack_deploy_token }}"
  loop_control:
    loop_var: slack_deploy_token
  when:
    - vault_wordpress_sites[site].slack_deploy_token is defined
    - vault_wordpress_sites[site].slack_deploy_token | length > 0
  delegate_to: localhost
  ignore_errors: yes
