---
- name: Send initial deployment notification to Slack
  slack:
    token: "{{ item.token }}"
    channel: "{{ item.channel }}"
    attachments:
      - text: "*{{ lookup('pipe', 'git config user.name') }}* has started deploying {{ site }} to *<https://{{ project.site_hosts | map(attribute='canonical') | first }}|{{ env }}>*"
        color: warning
  loop: "{{ slack_notifications }}"
  when:
    - slack_notifications is defined
    - slack_notifications | length > 0
  delegate_to: localhost
  ignore_errors: yes
