---
- name: Send successful deployment notification to Slack
  slack:
    token: "{{ slack_webhook_token }}"
    channel: slack_webhook_channel
    attachments:
      - text: "Deployment completed successfully"
        color: good
        fields:
          - title: Project
            value: "{{ site }}"
          - title: Environment
            value: "<{{ project.site_hosts | map(attribute='canonical') | first }}|{{ env }}>"
          - title: Commit
            value: "{{ git_clone.after }}"
          - title: User
            value: "{{ ansible_user }}"
  when: slack_webhook_token is defined and slack_webhook_token != ""
  delegate_to: localhost
