---
- name: Send successful deployment notification to Slack
  slack:
    token: "{{ slack_webhook_token }}"
    channel: slack_webhook_channel
    attachments:
      - text: "Deployment completed successfully"
        color: good
        fields:
          - title: Project
            value: "{{ site }}"
          - title: Environment
            value: "{{ env }}"
          - title: Commit
            value: "{{ git_clone.after }}"
  when: slack_webhook_token is defined and slack_webhook_token != ""
  delegate_to: localhost
